application: winfo-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /app/
  static_files: www/index.html
  upload: www/index.html

- url: /app
  static_dir: www

- url: /.*
  script: server.app

libraries:
- name: jinja2
  version: 2.6
